
typedef size_t dpa_u_hash_t;

typedef struct dpa_u_bo_inline dpa_u_bo_inline_t;
typedef const dpa_u_bo_inline_t dpa_u_bo_inline_ro_t;
typedef struct dpa_u_bo_simple_ro dpa_u_bo_simple_ro_t;
typedef struct dpa_u_bo_simple dpa_u_bo_simple_t;
typedef struct dpa__u_bo_unique_hashmap_entry dpa__u_bo_unique_hashmap_entry_t;
typedef const struct dpa__u_bo_unique_hashmap_entry* dpa_u_bo_unique_hashmap_t;
typedef struct dpa_u_bo_unique dpa_u_bo_unique_t;
typedef struct dpa_u_bo_ro dpa_u_bo_ro_t;
typedef struct dpa_u_bo dpa_u_bo_t;
typedef struct dpa_u_bo_refcounted_ro dpa_u_bo_refcounted_ro_t;

typedef struct dpa_u_bo_refcounted_ro dpa_u_bo_refcounted_ro_t;
typedef struct dpa_u_bo_refcounted dpa_u_bo_refcounted_t;
typedef struct dpa_u_bo_hashed_ro dpa_u_bo_hashed_ro_t;
typedef struct dpa_u_bo_hashed dpa_u_bo_hashed_t;
typedef struct dpa_u_bo_refcounted_hashed_ro dpa_u_bo_refcounted_hashed_ro_t;
typedef struct dpa_u_bo_refcounted_hashed dpa_u_bo_refcounted_hashed_t;

typedef const struct dpa_u_any_bo_inline dpa_u_any_bo_inline_t;
typedef dpa_u_any_bo_inline_t dpa_u_any_bo_inline_ro_t;
typedef const struct dpa_u_any_bo_simple_ro dpa_u_any_bo_simple_ro_t;
typedef const struct dpa_u_any_bo_simple dpa_u_any_bo_simple_t;
typedef const struct dpa_u_any_bo_unique_hashmap dpa_u_any_bo_unique_hashmap_t;
typedef const struct dpa_u_any_bo_unique dpa_u_any_bo_unique_t;
typedef const struct dpa_u_any_bo_ro dpa_u_any_bo_ro_t;
typedef const struct dpa_u_any_bo dpa_u_any_bo_t;

typedef const struct dpa_u_any_bo_refcounted_ro dpa_u_any_bo_refcounted_ro_t;
typedef const struct dpa_u_any_bo_refcounted dpa_u_any_bo_refcounted_t;
typedef const struct dpa_u_any_bo_hashed_ro dpa_u_any_bo_hashed_ro_t;
typedef const struct dpa_u_any_bo_hashed dpa_u_any_bo_hashed_t;
typedef const struct dpa_u_any_bo_refcounted_hashed_ro dpa_u_any_bo_refcounted_hashed_ro_t;

typedef const struct dpa_u_bo_gc_ro dpa_u_bo_gc_ro_t;
typedef const struct dpa_u_bo_with_hash_ro dpa_u_bo_with_hash_ro_t;
typedef const struct dpa_u_bo_with_hash dpa_u_bo_with_hash_t;
typedef const struct dpa_u_bo_with_refcount_ro dpa_u_bo_with_refcount_ro_t;
typedef const struct dpa_u_bo_with_refcount dpa_u_bo_with_refcount_t;
typedef const struct dpa_u_bo_with_refcount_and_hash_ro dpa_u_bo_with_refcount_and_hash_ro_t;

typedef struct dpa_u_bo_unique_hashmap_stats_s dpa_u_bo_unique_hashmap_stats_t;
typedef struct dpa__u_bo_a dpa__u_bo_a_t;
