#!/bin/sh

cd "$(dirname "$0")/.."

(
  find include/dpa/utils/ -iname '*.h' -not -iname '_*' -exec cat {} \;
  echo .
  printf "%s\n" "$1"
) | sed 's|#include *<dpa/utils/.*||g' \
  | sed 's/\\$/\x01\\/' \
  | cpp -x c -CC -P -std=c17 -Wall -Wextra -pedantic -D_DEFAULT_SOURCE - \
  | tail -n 1 \
  | sed 's/\x01/\n/g'
