#!/bin/bash

vars=( $(grep -roh '<var [^>]*name="[^"]*' docs/ | grep -o '[^"]*$' | sort -u) )
related=(
  "dpa_u_bo_inline_t DPA_U_BO_INLINE"
  "dpa_u_bo_unique_hashmap_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_bo_simple_ro_t DPA_U_BO_SIMPLE"
  "dpa_u_bo_simple_t DPA_U_BO_SIMPLE"
  "dpa_u_bo_unique_t DPA_U_BO_INLINE"
  "dpa_u_bo_unique_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_bo_ro_t DPA_U_BO_INLINE"
  "dpa_u_bo_ro_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_bo_ro_t DPA_U_BO_SIMPLE"
  "dpa_u_bo_t DPA_U_BO_INLINE"
  "dpa_u_bo_t DPA_U_BO_SIMPLE"
  "dpa_u_bo_hashed_ro_t DPA_U_BO_HASHED"
  "dpa_u_bo_hashed_t DPA_U_BO_HASHED"
  "dpa_u_bo_refcounted_ro_t DPA_U_BO_REFCOUNTED"
  "dpa_u_bo_refcounted_t DPA_U_BO_REFCOUNTED"
  "dpa_u_bo_refcounted_hashed_ro_t DPA_U_BO_REFCOUNTED_HASHED"
  "dpa_u_any_bo_inline_t DPA_U_BO_INLINE"
  "dpa_u_any_bo_unique_hashmap_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_any_bo_simple_ro_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_any_bo_simple_ro_t DPA_U_BO_SIMPLE"
  "dpa_u_any_bo_simple_ro_t DPA_U_BO_HASHED"
  "dpa_u_any_bo_simple_ro_t DPA_U_BO_REFCOUNTED"
  "dpa_u_any_bo_simple_ro_t DPA_U_BO_REFCOUNTED_HASHED"
  "dpa_u_any_bo_simple_t DPA_U_BO_SIMPLE"
  "dpa_u_any_bo_simple_t DPA_U_BO_HASHED"
  "dpa_u_any_bo_simple_t DPA_U_BO_REFCOUNTED"
  "dpa_u_any_bo_unique_t DPA_U_BO_INLINE"
  "dpa_u_any_bo_unique_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_any_bo_ro_t DPA_U_BO_INLINE"
  "dpa_u_any_bo_ro_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_any_bo_ro_t DPA_U_BO_SIMPLE"
  "dpa_u_any_bo_ro_t DPA_U_BO_HASHED"
  "dpa_u_any_bo_ro_t DPA_U_BO_REFCOUNTED"
  "dpa_u_any_bo_ro_t DPA_U_BO_REFCOUNTED_HASHED"
  "dpa_u_any_bo_t DPA_U_BO_INLINE"
  "dpa_u_any_bo_t DPA_U_BO_SIMPLE"
  "dpa_u_any_bo_t DPA_U_BO_HASHED"
  "dpa_u_any_bo_t DPA_U_BO_REFCOUNTED"
  "dpa_u_any_bo_hashed_ro_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_any_bo_hashed_ro_t DPA_U_BO_HASHED"
  "dpa_u_any_bo_hashed_t DPA_U_BO_HASHED"
  "dpa_u_any_bo_refcounted_ro_t DPA_U_BO_REFCOUNTED"
  "dpa_u_any_bo_refcounted_ro_t DPA_U_BO_REFCOUNTED_HASHED"
  "dpa_u_any_bo_refcounted_t DPA_U_BO_REFCOUNTED"
  "dpa_u_any_bo_refcounted_hashed_ro_t DPA_U_BO_REFCOUNTED_HASHED"
  "dpa_u_bo_with_hash_ro_t DPA_U_BO_INLINE"
  "dpa_u_bo_with_hash_ro_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_bo_with_hash_ro_t DPA_U_BO_HASHED"
  "dpa_u_bo_with_hash_ro_t DPA_U_BO_REFCOUNTED_HASHED"
  "dpa_u_bo_with_hash_t DPA_U_BO_INLINE"
  "dpa_u_bo_with_hash_t DPA_U_BO_HASHED"
  "dpa_u_bo_gc_ro_t DPA_U_BO_INLINE"
  "dpa_u_bo_gc_ro_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_bo_gc_ro_t DPA_U_BO_REFCOUNTED"
  "dpa_u_bo_gc_ro_t DPA_U_BO_REFCOUNTED_HASHED"
  "dpa_u_bo_with_refcount_ro_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_bo_with_refcount_ro_t DPA_U_BO_REFCOUNTED"
  "dpa_u_bo_with_refcount_ro_t DPA_U_BO_REFCOUNTED_HASHED"
  "dpa_u_bo_with_refcount_t DPA_U_BO_REFCOUNTED"
  "dpa_u_bo_with_refcount_and_hash_ro_t DPA_U_BO_UNIQUE_HASHMAP"
  "dpa_u_bo_with_refcount_and_hash_ro_t DPA_U_BO_REFCOUNTED_HASHED"
)

rrelated=()
for kv in "${related[@]}"
do
  read -r k v <<<"$kv"
  rrelated+=("$v $k")
done

find-matches(){
  g="$1"; shift
  for e in "$@"
  do
    case "$e" in $g) echo "$e";; esac
  done
}

find-matches-graph(){
  g="$1"; shift
  for kv in "$@"
  do
    read -r k v <<<"$kv"
    case "$k" in $g) echo "$v";; esac
  done | sort -u
}

(

for selector in "${vars[@]}"
do
  r=( $(find-matches-graph "$selector" "${related[@]}") )
  if [ "${#r[@]}" -gt 0 ]
  then
    printf ":root:has(var[name=\"%s\"]:hover) :is(" "$selector"
    printf "var[name=\"%s\"]" "$r"
    if [ "${#r[@]}" -gt 1 ]
      then printf ",var[name=\"%s\"]" "${r[@]:1}"
    fi
    echo "),"
  fi
done
cat <<EOF
x:root {
  color: var(--var-related-color);
}

EOF

for selector in "${vars[@]}"
do
  r=( $(find-matches-graph "$selector" "${rrelated[@]}") )
  if [ "${#r[@]}" -gt 0 ]
  then
    printf ":root:has(var[name=\"%s\"]:hover) :is(" "$selector"
    printf "var[name=\"%s\"]" "$r"
    if [ "${#r[@]}" -gt 1 ]
      then printf ",var[name=\"%s\"]" "${r[@]:1}"
    fi
    echo "),"
  fi
done
cat <<EOF
x:root {
  color: var(--var-rrelated-color);
}

EOF

for selector in "${vars[@]}"
do
  matches=( $(find-matches "$selector" "${vars[@]}") )
  printf ":root:has(var[name=\"%s\"]:hover) :is(" "$selector"
  printf "var[name=\"%s\"]" "$matches"
  if [ "${#matches[@]}" -gt 1 ]
    then printf ",var[name=\"%s\"]" "${matches[@]:1}"
  fi
  echo "),"
done
cat <<EOF
x:root {
  color: var(--var-active-color);
}

EOF

) | tee docs/css/var.css
