#!/bin/bash

implemented="$(
  ctags --c-kinds=+pxd -R --output-format=json include/ |
    jq -r 'select(.scopeKind == null) | .name' |
    grep -i dpa_u_ | grep -iv '_[pgsh]$' | sort -u
)"

implemented_file="$(
  ctags --c-kinds=+pxd -R --output-format=json include/ |
    jq -r 'select(.scopeKind == null) | .path[8:] + "\t" + .name' |
    sort -u
)"

# Remove things like struct types which have a typedef, only keep the typedef, we add a _t to those.
implemented="$(comm -23 <(echo "$implemented") <(sed -n 's/_t$//p' <<<"$implemented" | sort -u))"
implemented_count="$(echo "$implemented" | wc -l)"
implemented_count="$((implemented_count - 1))"

documented="$( (
  grep -rohi ' id="dpa_u_[^"]*' docs/ | grep -o '[^"]*$'
#   grep -rohi '<a [^>]*href="[^"#]*#[^"]*' docs/ | grep 'class="var"' | grep -o '[^#]*$'
) | grep -v '_$' | sort -u )"
documented_count="$(echo "$documented" | wc -l)"
documented_count="$((documented_count - 1))"

all="$(
  (
    echo "$implemented"
    echo "$documented"
  ) | sort -u
)"
total="$(echo "$all" | wc -l)"
total="$((total - 1))"

iandd="$(comm -12 <(echo "$implemented") <(echo "$documented"))"
iandd_count="$(echo "$iandd" | wc -l)"
iandd_count="$((iandd_count - 1))"

unimplemented="$(comm -13 <(echo "$implemented") <(echo "$documented"))"
unimplemented_count="$(echo "$unimplemented" | wc -l)"
unimplemented_count="$((unimplemented_count - 1))"
undocumented="$(comm -23 <(echo "$implemented") <(echo "$documented"))"
undocumented_count="$(echo "$undocumented" | wc -l)"
undocumented_count="$((undocumented_count - 1))"

echo "total: $total"
echo "implemented and documented: $iandd_count ($((iandd_count * 100 / total))%)"
echo "unimplemented: $unimplemented_count ($((unimplemented_count * 100 / total))%)"
echo "undocumented: $undocumented_count ($((undocumented_count * 100 / total))%)"
echo "implemented: $implemented_count ($((implemented_count * 100 / total))%)"
echo "documented: $documented_count ($((documented_count * 100 / total))%)"

echo
echo "# Unimplemented"
echo
echo "$unimplemented"

echo
echo "# Undocumented"
lastfile=""
while IFS=$'\t' read -r file symbol
do
  if ! grep -qxF "$symbol" <<<"$undocumented"
    then continue
  fi
  if [ "$lastfile" != "$file" ]
  then
    lastfile="$file"
    echo
    echo "<$file>"
  fi
  echo "$symbol"
done <<<"$implemented_file"
