#!/bin/bash
set -e
shopt -s globstar nullglob

cd include/dpa/utils/_bo/
for d in */
do (
  exec >"${d%/}.h"
  cd "$d"
  incpath="$(realpath . | sed -n 's .*/include/  p')"
  for f in **/*.h
  do
    [ "$f" != 'all.h' ] || continue
    printf "#include <%s/%s>\n" "$incpath" "$f"
  done
); done
