#!/bin/bash

set -e

genexports(){
  find "$@" -iname "*.h" -not -iname "_*" -exec cat {} \; | sed -n 's/.* inline \([^(]* dpa_[a-zA-Z0-9_]*([^)]*)\).*/extern \1;/p' | sort -u
}

declare -A extra
extra=(
  ["bo.h"]="_bo/"
  ["hash.h"]="_hash/"
)

root="$(realpath "$(dirname "$0")/..")"
cd "$root"

(
  cd include/dpa/utils/
  for h in *.h
  do (
    f="$root/src/gen/$h.c"
    exec >"$f"
    echo "#define DPA__U_GEN_EXPORTS"
    printf "#include <dpa/utils/%s>\n\n" "$h"
    genexports "$h" ${extra["$h"]}
    if [ "$(wc -l <"$f")" -le 3 ]
      then rm "$f"
    fi
  ); done
)
