#!/bin/bash

msvcdir="$(printf '%s\n' "/mnt/c/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/"*/ | tail -n 1)"
export PATH="$PATH:${msvcdir}bin/Hostx64/x64"

options="$1"; shift
archive="$1"; shift

args=(
  "lib.exe"
  "/OUT:$archive"
)

case "$options" in
  d)
     for f
       do args+=("/REMOVE:$f")
     done
  ;; 
  q|r)
     for f
       do args+=("$f")
     done
  ;; 
esac

quote(){
  local quoted=${1//\'/\'\\\'\'};
  printf "'%s'" "$quoted"
}

print_cmd(){
  qargs=()
  for x in "$@"
  do
    qargs+=("$(quote "$x")")
  done
  echo "${qargs[@]}" >&2
}

print_cmd "${args[@]}"
exec "${args[@]}"
